<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lecciones</title>
    <script src="/js/domus-achievements.js"></script>
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body class="app-bg">
<main class="layout">
    <div id="sidebar-overlay" class="sidebar-overlay"></div>
    <aside id="sidebar" class="sidebar">
        <button id="sidebar-close" class="sidebar-close" type="button">x</button>
        <div class="sidebar-logo-wrap"><img class="sidebar-logo" src="/img/domus_logo.png" alt="Domus logo"></div>
        <section class="profile-card"><p id="sidebar-user-name" class="profile-name">Usuario</p><a id="sidebar-user-level" class="profile-level" href="/levels" style="display:none;color:inherit;text-decoration:none;">Cargando nivel...</a></section>
        <div id="sidebar-scroll" class="sidebar-scroll">
            <nav class="sidebar-nav">
                <a class="sidebar-link" href="/account"><span class="nav-icon">&bull;</span><span>Inicio</span></a>
                <a class="sidebar-link" href="/account/users"><span class="nav-icon">&bull;</span><span>Usuarios</span></a>
                <a id="loans-link" class="sidebar-link" href="/account/loans"><span class="nav-icon">&bull;</span><span>Prestamos</span></a>
                <a id="transfers-link" class="sidebar-link" href="/parent/transfers"><span class="nav-icon">&bull;</span><span>Dar dinero</span></a>
                <a id="allowances-link" class="sidebar-link" href="/parent/allowances"><span class="nav-icon">&bull;</span><span>Mesadas</span></a>
                <a id="savings-boxes-link" class="sidebar-link" href="/parent/savings-boxes"><span class="nav-icon">&bull;</span><span>Cajas de ahorro</span></a>
                <a id="goals-link" class="sidebar-link" href="/child/goals"><span class="nav-icon">&bull;</span><span>Metas</span></a>
                <a id="tasks-link" class="sidebar-link" href="/child/tasks"><span class="nav-icon">&bull;</span><span>Tareas</span></a>
                <a id="domus-points-link" class="sidebar-link" href="/account/domus-points"><span class="nav-icon">&bull;</span><span>Puntos Domus</span></a>
                <a class="sidebar-link is-active" href="/account/education"><span class="nav-icon">&bull;</span><span>Educacion</span></a>
            </nav>
            <div id="scroll-hint" class="scroll-hint">Desliza para ver mas</div>
        </div>
    </aside>
    <section class="page content card">
        <div class="top-row"><button id="menu-btn" class="btn blue-btn menu-toggle" type="button">Menu</button><button id="logout-btn" class="btn btn-inline gold-btn right" type="button">Cerrar sesion</button></div>
        <p class="brand mt-2">DOMUS</p>
        <h1 id="course-title">Curso</h1>
        <p id="course-subtitle" class="subtitle">Cargando lecciones...</p>
        <div id="course-content" class="mt-2"></div>
    </section>
</main>
<script>
const SECONDS_TO_COMPLETE_LESSON=30;
const API_BASE='/api',TOKEN_KEY='parent_auth_token';
const logoutButton=document.getElementById('logout-btn'),menuButton=document.getElementById('menu-btn'),sidebar=document.getElementById('sidebar'),sidebarUserName=document.getElementById('sidebar-user-name'),sidebarUserLevel=document.getElementById('sidebar-user-level'),sidebarClose=document.getElementById('sidebar-close'),sidebarOverlay=document.getElementById('sidebar-overlay'),sidebarScroll=document.getElementById('sidebar-scroll'),scrollHint=document.getElementById('scroll-hint'),tasksLink=document.getElementById('tasks-link'),loansLink=document.getElementById('loans-link'),transfersLink=document.getElementById('transfers-link'),allowancesLink=document.getElementById('allowances-link'),savingsBoxesLink=document.getElementById('savings-boxes-link'),goalsLink=document.getElementById('goals-link'),domusPointsLink=document.getElementById('domus-points-link'),courseTitle=document.getElementById('course-title'),courseSubtitle=document.getElementById('course-subtitle'),courseContent=document.getElementById('course-content');
let courseState=null,completionTimer=null,secondsRemaining=SECONDS_TO_COMPLETE_LESSON,isCompletingLesson=false;
function getToken(){return localStorage.getItem(TOKEN_KEY);} function clearToken(){localStorage.removeItem(TOKEN_KEY);} function openSidebar(){sidebar.classList.add('is-open');sidebarOverlay.classList.add('is-open');} function closeSidebar(){sidebar.classList.remove('is-open');sidebarOverlay.classList.remove('is-open');}
function updateScrollHint(){const canScroll=sidebarScroll.scrollHeight>sidebarScroll.clientHeight;const nearBottom=sidebarScroll.scrollTop+sidebarScroll.clientHeight>=sidebarScroll.scrollHeight-4;scrollHint.classList.toggle('is-visible',canScroll&&!nearBottom);}
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function getCourseId(){const match=window.location.pathname.match(/\/account\/education\/courses\/(\d+)/);return match?match[1]:null;}
async function apiRequest(path,method,payload){const token=getToken();const headers={Accept:'application/json','Content-Type':'application/json'};if(token){headers.Authorization='Bearer '+token;}const response=await fetch(API_BASE+path,{method,headers,body:payload?JSON.stringify(payload):undefined});const data=await response.json().catch(()=>({}));if(!response.ok){throw {status:response.status,data};}return data;}
async function loadUserHeader(){const me=await apiRequest('/me','GET');const role=me.user?.role||'parent';sidebarUserName.textContent=me.user?.name||'Usuario';if(tasksLink){tasksLink.href=(role==='parent'?'/parent/tasks':'/child/tasks');}if(transfersLink){transfersLink.classList.toggle('is-hidden',role!=='parent');}if(allowancesLink){allowancesLink.classList.toggle('is-hidden',role!=='parent');}if(savingsBoxesLink){savingsBoxesLink.href=(role==='parent'?'/parent/savings-boxes':'/child/savings-boxes');savingsBoxesLink.classList.toggle('is-hidden',false);}if(goalsLink){goalsLink.href='/child/goals';goalsLink.classList.toggle('is-hidden',role==='parent');}if(loansLink){loansLink.href=(role==='parent'?'/parent/loans':'/member/loans');}if(domusPointsLink){domusPointsLink.href=(role==='parent'?'/parent/domus-points':'/child/domus-points');}if(role==='child'||role==='member'){sidebarUserLevel.style.display='block';try{const points=await apiRequest('/child/domus-points','GET');const level=points.level;sidebarUserLevel.textContent=level?('Nivel '+Number(level.level_number||1)+' - '+level.name):'Sin nivel';}catch(_error){sidebarUserLevel.textContent='Sin nivel';}}else{sidebarUserLevel.style.display='none';}}
function youtubeEmbed(url){const match=String(url||'').match(/(?:v=|youtu\.be\/)([A-Za-z0-9_-]{11})/);return match?('https://www.youtube.com/embed/'+match[1]):'';}
function getCourseProgressPercentage(){const completed=Number(courseState?.progress?.completed_lessons||0);const total=Math.max(1,Number(courseState?.progress?.total_lessons||0));return Math.round((completed/total)*100);}
function renderExamRewardInfo(reward){if(!reward){return '';}const approvedPercentage=Number(reward.approved_percentage||0);const excellentPercentage=Number(reward.excellent_percentage||0);const approvedPoints=Number(reward.approved_points||0);const excellentPoints=Number(reward.excellent_points||0);const awardedText=Number(reward.awarded_points_total||0)>0?'<p class="quick-card-subtitle"><strong>Hasta ahora llevas '+Number(reward.awarded_points_total||0)+' puntos Domus ganados en este examen.</strong></p>':'';const statusMessage=reward.message?'<p class="quick-card-subtitle"><strong>'+escapeHtml(reward.message)+'</strong></p>':'';return '<section class="quick-card mt-1"><p class="quick-card-title">Puntos Domus de este examen</p><p class="quick-card-subtitle"><strong>Si lo apruebas con al menos '+approvedPercentage+'%, ganaras '+approvedPoints+' puntos Domus.</strong></p><p class="quick-card-subtitle"><strong>Si logras '+excellentPercentage+'% o mas, ganaras '+excellentPoints+' puntos Domus mas.</strong></p>'+awardedText+statusMessage+'</section>';}
function renderExamLockedPart(progressPercentage,reward){return '<section class="education-card"><p class="education-card-eyebrow">Examen bloqueado</p><p class="education-card-title">Necesitas mas avance para presentar este examen</p><p class="education-card-text">Necesitas un minimo de 50% de avance en este curso. Actualmente llevas '+progressPercentage+'%.</p>'+renderExamRewardInfo(reward)+'</section>';}
function renderAssessmentPart(part){const questions=Array.isArray(part.meta?.questions)?part.meta.questions:[];const title=part.type==='exam'?'Examen':'Quiz';const progressPercentage=getCourseProgressPercentage();if(part.type==='exam'&&progressPercentage<50){return renderExamLockedPart(progressPercentage,part.reward);}const lastResult=part.type==='exam'&&part.last_result?'<p class="quick-card-subtitle">Ultima vez: '+Number(part.last_result.score||0)+' / '+Number(part.last_result.total_questions||0)+' ('+Number(part.last_result.percentage||0)+'%)</p>':'';const rewardInfo=part.type==='exam'?renderExamRewardInfo(part.reward):'';return '<section class="education-card"><p class="education-card-eyebrow">'+title+'</p><p class="education-card-title">'+escapeHtml(part.content||title)+'</p>'+lastResult+rewardInfo+'<form class="assessment-form" data-part-id="'+Number(part.id)+'" data-assessment-type="'+escapeHtml(part.type)+'">'+questions.map((question,index)=>'<div class="field mt-1"><p class="lesson-copy"><strong>'+(index+1)+'.</strong> '+escapeHtml(question.question||'Pregunta')+'</p><label class="choice-pill"><input type="radio" name="question-'+Number(part.id)+'-'+escapeHtml(question.uuid||String(index))+'" value="a" data-question-uuid="'+escapeHtml(question.uuid||String(index))+'"> '+escapeHtml(question.option_a||'')+'</label><label class="choice-pill"><input type="radio" name="question-'+Number(part.id)+'-'+escapeHtml(question.uuid||String(index))+'" value="b" data-question-uuid="'+escapeHtml(question.uuid||String(index))+'"> '+escapeHtml(question.option_b||'')+'</label><label class="choice-pill"><input type="radio" name="question-'+Number(part.id)+'-'+escapeHtml(question.uuid||String(index))+'" value="c" data-question-uuid="'+escapeHtml(question.uuid||String(index))+'"> '+escapeHtml(question.option_c||'')+'</label><label class="choice-pill"><input type="radio" name="question-'+Number(part.id)+'-'+escapeHtml(question.uuid||String(index))+'" value="d" data-question-uuid="'+escapeHtml(question.uuid||String(index))+'"> '+escapeHtml(question.option_d||'')+'</label></div>').join('')+'<div class="lesson-status-row mt-1"><button class="btn gold-btn btn-inline" type="submit">Enviar '+title.toLowerCase()+'</button><div class="feedback-box is-hidden" data-assessment-result></div></div></form></section>';}
function renderPart(part){if(part.type==='title'){return '<h3 class="lesson-section-title">'+escapeHtml(part.content)+'</h3>';}if(part.type==='text'||part.type==='string'){return '<p class="lesson-copy">'+escapeHtml(part.content)+'</p>';}if(part.type==='image'||part.type==='image_url'){return '<img class="edu-image" src="'+escapeHtml(part.content)+'" alt="Leccion" loading="lazy">';}if(part.type==='video'||part.type==='video_youtube'){const embed=youtubeEmbed(part.content);return embed?'<div class="video-wrap"><iframe src="'+embed+'" title="Video de leccion" loading="lazy" allowfullscreen></iframe></div>':'<p class="lesson-copy">Video invalido</p>';}if(part.type==='quiz'||part.type==='exam'){return renderAssessmentPart(part);}return '<p class="lesson-copy">'+escapeHtml(part.content)+'</p>';}
function stopCompletionTimer(){if(completionTimer){clearInterval(completionTimer);completionTimer=null;}}
function updateCountdownText(){const countdown=document.getElementById('lesson-countdown');if(!countdown){return;}const lesson=courseState?.current_lesson;if(!lesson){countdown.textContent='';return;}if(lesson.is_completed){countdown.textContent='Leccion completada.';return;}countdown.textContent='Se marcara como completada en '+secondsRemaining+' segundo(s).';}
function applyCompletedLessonState(){const lesson=courseState?.current_lesson;if(!lesson){return;}lesson.is_completed=true;const progress=courseState?.progress||null;if(progress){const completedNow=Number(progress.completed_lessons||0);const lessonItems=Array.isArray(courseState?.lessons)?courseState.lessons:[];const lessonInList=lessonItems.find(item=>Number(item.id)===Number(lesson.id));if(lessonInList&&!lessonInList.is_completed){lessonInList.is_completed=true;progress.completed_lessons=completedNow+1;}}const lessonStatusPill=document.getElementById('lesson-status-pill');if(lessonStatusPill){lessonStatusPill.textContent='Completada';}const countdown=document.getElementById('lesson-countdown');if(countdown){countdown.textContent='Leccion completada.';}const lessonButton=document.querySelector('[data-lesson-id="'+lesson.id+'"]');if(lessonButton){lessonButton.classList.add('is-completed');if(!lessonButton.querySelector('.member-badge')){lessonButton.insertAdjacentHTML('beforeend','<span class="member-badge">Completada</span>');}}const progressSummary=document.getElementById('progress-summary-pill');if(progressSummary&&progress){progressSummary.textContent=Number(progress.completed_lessons||0)+' / '+Number(progress.total_lessons||0)+' completadas';}}
async function markCurrentLessonCompleted(){if(isCompletingLesson||!courseState?.current_lesson||courseState.current_lesson.is_completed){return;}isCompletingLesson=true;try{await apiRequest('/education/lessons/'+courseState.current_lesson.id+'/complete','POST',{});applyCompletedLessonState();}catch(error){const countdown=document.getElementById('lesson-countdown');if(countdown){countdown.textContent='No se pudo marcar la leccion.';}}finally{isCompletingLesson=false;}}
function startCompletionTimer(){stopCompletionTimer();const lesson=courseState?.current_lesson;secondsRemaining=SECONDS_TO_COMPLETE_LESSON;updateCountdownText();if(!lesson||lesson.is_completed){return;}completionTimer=setInterval(async()=>{secondsRemaining-=1;updateCountdownText();if(secondsRemaining<=0){stopCompletionTimer();await markCurrentLessonCompleted();}},1000);}
function bindLessonButtons(){document.querySelectorAll('[data-lesson-id]').forEach(button=>{button.addEventListener('click',()=>{const lessonId=button.getAttribute('data-lesson-id');loadCourse(lessonId);});});}
function bindAssessmentForms(){document.querySelectorAll('.assessment-form').forEach(form=>{form.addEventListener('submit',async event=>{event.preventDefault();const partId=form.getAttribute('data-part-id');const assessmentType=form.getAttribute('data-assessment-type');const resultBox=form.querySelector('[data-assessment-result]');const answers=[];const grouped=new Map();form.querySelectorAll('input[type="radio"][data-question-uuid]').forEach(input=>{const questionUuid=input.getAttribute('data-question-uuid');if(!grouped.has(questionUuid)){grouped.set(questionUuid,input.name);}});grouped.forEach((inputName,questionUuid)=>{const selected=form.querySelector('input[name="'+CSS.escape(inputName)+'"]:checked');if(selected){answers.push({question_uuid:questionUuid,answer:selected.value});}});if(!answers.length){resultBox.textContent='Responde al menos una pregunta.';resultBox.className='feedback-box feedback-error';return;}try{const response=await apiRequest('/education/lesson-parts/'+partId+'/submit','POST',{answers});let feedback=(assessmentType==='exam'?'Resultado del examen: ':'Resultado del quiz: ')+Number(response.score||0)+' / '+Number(response.total_questions||0)+' ('+Number(response.percentage||0)+'%)';if(assessmentType==='exam'&&response.reward?.message){feedback+=' | '+response.reward.message;}resultBox.textContent=feedback;resultBox.className='feedback-box feedback-success';if(window.handleDomusAchievements){window.handleDomusAchievements(response.achievements);}if(assessmentType==='exam'){await loadCourse(courseState?.current_lesson?.id||null);}}catch(error){resultBox.textContent=error.data?.message||'No se pudo revisar esta evaluacion.';resultBox.className='feedback-box feedback-error';}});});}
function renderCourse(){const category=courseState?.category||{};const course=courseState?.course||{};const lessons=courseState?.lessons||[];const currentLesson=courseState?.current_lesson;const progress=courseState?.progress||{};courseTitle.textContent=course.title||'Curso';courseSubtitle.textContent=course.description||'Selecciona una leccion.';if(!currentLesson){courseContent.innerHTML='<a class="back-link" href="/account/education/categories/'+category.id+'/courses">Volver a cursos</a><section class="quick-card mt-2"><p class="quick-card-title">Sin lecciones</p><p class="quick-card-subtitle">Este curso aun no tiene lecciones activas.</p></section>';return;}courseContent.innerHTML='<div class="lesson-status-row"><a class="back-link" href="/account/education/categories/'+category.id+'/courses">Volver a cursos</a><span id="progress-summary-pill" class="progress-pill">'+Number(progress.completed_lessons||0)+' / '+Number(progress.total_lessons||0)+' completadas</span></div><section class="education-shell mt-2"><aside class="lesson-sidebar-panel"><p class="quick-card-title">Lecciones</p><div class="lesson-list">'+lessons.map(lesson=>'<button class="lesson-switch'+(lesson.id===currentLesson.id?' is-active':'')+(lesson.is_completed?' is-completed':'')+'" type="button" data-lesson-id="'+lesson.id+'"><span class="lesson-counter">Leccion '+lesson.position+'</span><span>'+escapeHtml(lesson.title||lesson.name)+'</span>'+(lesson.is_completed?'<span class="member-badge">Completada</span>':'')+'</button>').join('')+'</div></aside><section class="lesson-view-card">'+(course.image_url?'<img class="edu-image" src="'+escapeHtml(course.image_url)+'" alt="'+escapeHtml(course.title)+'" loading="lazy">':'')+'<p class="education-card-eyebrow">'+escapeHtml(category.name||'Curso')+'</p><h2 class="lesson-view-title">'+escapeHtml(currentLesson.title||currentLesson.name)+'</h2><p class="lesson-copy">'+escapeHtml(currentLesson.description||'')+'</p><div class="lesson-status-row"><span id="lesson-status-pill" class="progress-pill">'+(currentLesson.is_completed?'Completada':'En progreso')+'</span><span id="lesson-countdown" class="lesson-countdown"></span></div><div class="lesson-parts mt-2">'+(currentLesson.parts||[]).map(renderPart).join('')+'</div></section></section>';bindLessonButtons();bindAssessmentForms();updateCountdownText();startCompletionTimer();}
async function loadCourse(selectedLessonId=null){const courseId=getCourseId();if(!getToken()){window.location.href='/login';return;}if(!courseId){courseSubtitle.textContent='Curso invalido.';return;}stopCompletionTimer();try{if(!courseState){await loadUserHeader();}const suffix=selectedLessonId?('?lesson_id='+selectedLessonId):'';courseState=await apiRequest('/education/courses/'+courseId+suffix,'GET');renderCourse();}catch(error){if(error.status===401){clearToken();window.location.href='/login';return;}courseContent.innerHTML='<section class="quick-card"><p class="quick-card-title">Error</p><p class="quick-card-subtitle">No se pudo cargar el curso.</p></section>';}}
logoutButton.addEventListener('click',async()=>{try{await apiRequest('/logout','POST');}catch(e){}finally{clearToken();window.location.href='/login';}});
menuButton.addEventListener('click',()=>{if(sidebar.classList.contains('is-open')){closeSidebar();return;}openSidebar();updateScrollHint();});sidebarClose.addEventListener('click',closeSidebar);sidebarOverlay.addEventListener('click',closeSidebar);sidebarScroll.addEventListener('scroll',updateScrollHint);window.addEventListener('resize',()=>{if(window.innerWidth>=768){closeSidebar();}updateScrollHint();});window.addEventListener('beforeunload',stopCompletionTimer);
updateScrollHint();loadCourse();
</script>
</body>
</html>
